### ISSUE TITLE
Code splitting?

### ISSUE THREAD

**Issue by endigma** [expung3d/Enhanced-Zeus-Modules#1]
You could probably make a script or binary using a template tool to allow code splitting your 20000 line script into more readable bits. Would make contribution and reading code a lot easier. You could set up a github action to construct the finished script and create a release.

**Comment by endigma** [comment]
Using something more advanced like https://github.com/kataras/blocks you could probably even get like macro-like functionality working, allowing you to shorthand repeated code. Would be a foundation for a sort of SQF compiler.

**Comment by expung3d** [comment]
I don't think this is ever gunna happen. It just doesn't really need to be done because of the modularity systems I've added. _Maybe_ it would make it more maintainable or easy to contribute to but most people don't do that so it's really a non-issue.
