### ISSUE TITLE
Transport Unload Waypoint Issues

### ISSUE THREAD

**Issue by GustavVatsug** [expung3d/Enhanced-Zeus-Modules#10]
Transport unload for custom faction vehicles with troops inside does not work. The vehicle arrives at the waypoint but the passengers remains inside. Not really that big of an issue since you can manually have the passengers leave the vehicle with the EDIT tab, but it'd be nice to have it working if possible.
![image_2023-01-06_200016713](https://user-images.githubusercontent.com/119013268/211081004-01baff65-2245-471b-a082-956e03c8eb70.png)

**Comment by expung3d** [comment]
Cannot reproduce the issue. Transport unload is working with custom factions.
