### ISSUE TITLE
[REQUEST] - Open Top Hunter

### ISSUE THREAD

**Issue by PenieWenie** [expung3d/Enhanced-Zeus-Modules#14]
**What feature would you like to see added?**
i made an open top hunter, it has the ablity to switch between seats from gunner to passengers and it detects when seats are full or empty and removes the ability to enter them based on this. it can be equipped with a minigun or 50 cal and in the future i will be adding a gunner shield and little gunner protection box like you see on mraps. the only think stopping me at the moment is finding the "bone" for the turret left and right rotation. i have found the bone for the gun position and will be implementing a small shield shortly. (bone is for addaction)

**Additional context**
![image](https://user-images.githubusercontent.com/125714004/219827728-f3401cbf-e851-4819-90aa-7112f3e3ee4a.png)

https://steamcommunity.com/sharedfiles/filedetails/?id=2934979397

**Comment by PenieWenie** [comment]
all i ask is that i get a credit on the module or whatever

**Comment by PenieWenie** [comment]
Also 50cal version will be uploaded later

**Comment by Zaco-Kick** [comment]
meh
