### ISSUE TITLE
[REQUEST] - suppresion module

### ISSUE THREAD

**Issue by PenieWenie** [expung3d/Enhanced-Zeus-Modules#15]
**What feature would you like to see added?**
Current suppression module sucks, we need a better one. I can probsly develop it I just need to know where I can find the code for the current one.

**Comment by PenieWenie** [comment]
Ability to use in on vics would also be nice, infinite ammo and alonger shoot time is also a good idea

**Comment by M9-SD** [comment]
"I just need to know where I can find the code for the current one"
Use CTRL+F bro:
MAZ_EZM_fnc_suppressiveFireModule (line 5564)
https://github.com/expung3d/Enhanced-Zeus-Modules/blob/main/ZAM_fnc_EZMLiteV2.0.3.sqf#L5564

**Comment by expung3d** [comment]
This was updated in [V2.1.2](https://github.com/expung3d/Enhanced-Zeus-Modules/releases/tag/V2.1.2)
