### ISSUE TITLE
[BUG] - Minefield Tool Spawns underground

### ISSUE THREAD

**Issue by Kaank2006** [expung3d/Enhanced-Zeus-Modules#19]
**Describe the bug**
The "Create minefield" tool spawns mines under the map.

**To Reproduce**
1. Go to any map, easiest to see is virtual reality
2. Click on "Create Minefield"
3. Select preferred amount, does not matter
4. Spawn a mine specialist and see that the mines are underground.

**Expected behavior**
I expected the minese to behave normally, as in spawn above ground.

**Screenshots**
![image](https://user-images.githubusercontent.com/57836764/230562084-4721dc3d-8fd9-462f-ba2d-0754216c749d.png)

**Comment by Kaank2006** [comment]
Possible workaround: after placing the minefield, granted they are a small amount, you can deactivate and place them again with a mine specialist.

**Comment by expung3d** [comment]
Issue is confirmed.

**Comment by expung3d** [comment]
Fixed as of V2.0.9
