### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by ColdWasabi** [expung3d/Enhanced-Zeus-Modules#23]
**Describe the bug**
The remove editable objects button will not work. You press it and the yellow object icons remain.

**To Reproduce**
1. Right-click near/on the object
2. press remove editable objects any range applies

**Expected behavior**
I press the button and the objects icon disappears, I can not edit it but it remains visible.

**Screenshots**

**Additional context**
I've tried it on every map, uninstalled and reinstalled EZM and it still won't work.

**Comment by Zaco-Kick** [comment]
Cant Reproduce
