### ISSUE TITLE
[REQUEST] - Remove destroyed buildings from MAZ_EZM_fnc_deleteClutterModule

### ISSUE THREAD

**Issue by Zaco-Kick** [expung3d/Enhanced-Zeus-Modules#25]
Remove destroyed buildings from delete clutter fnc, zeuses will delete clutter during missions to delete bodies, but will accidentally delete half the town with them, often with players using them for cover.
It may be better to add specific ruins to a new module or not have them get deleted at all.

**Comment by expung3d** [comment]
Implemented with #7c4e9c6
