### ISSUE TITLE
[BUG] - BattleEye remoteExec kick after interface loads

### ISSUE THREAD

**Issue by LucSon-bat** [expung3d/Enhanced-Zeus-Modules#46]
**Describe the bug**
After placing down EZM and continuing with loading the interface, the interface loads 75% of the way before I get kicked via BattlEye. The specific error is remoteExec Restriction #105.

**To Reproduce**
1. Load any Zeus mission in a public server
2. While in the Game Master slot, place down Enhanced Zeus Modules
3. Adjust settings and press OK

**Expected behavior**
I expected the EZM interface to load fine.

**Screenshots**
![EZM_Bug](https://github.com/user-attachments/assets/5eff7d4c-cb82-451e-a33c-3490f52b9018)

**Additional context**
It is worth noting that I have seen other people use EZM fine post-update, however I have not been able to get EZM to work.

**Comment by expung3d** [comment]
This was fixed with a change to V2.1.2

https://github.com/expung3d/Enhanced-Zeus-Modules/commit/01aa687b72969d890431e1c76f0ff2b5d7359730

Cause was a spaghetti code average FPS function that was overloading BI servers with logs.
