### ISSUE TITLE
[REQUEST] - Zeus Teleport Keybind

### ISSUE THREAD

**Issue by Venom-au** [expung3d/Enhanced-Zeus-Modules#48]
**What feature would you like to see added?**
An addition to the current Keybinds of EZM, A Keybind which allows you to teleport  without needing to go look into the modules tab. 

**Describe alternatives you've considered**
N/A

**Additional context**
Using code from another EZM Script, I've been able to create this keybind and implement it into EZM, Just wasn't sure how exactly I could contribute it to the main script, if that be DM it or making a pull request etc. Unsure if this script in anyway can be 'Optimised' from what it already is considering it's so simple, So I havent bothered to change it at all, But you guys would know better in that aspect so if at all, I'd let you deal with it.

**Comment by expung3d** [comment]
Why use a keybind when you can just do RMB and then immediately LMB? The context menu's first action when you haven't selected something is always "teleport here".

https://github.com/user-attachments/assets/762f93a5-dbe2-4bc7-9cb3-d278c576f6d4

**Comment by Venom-au** [comment]
Yep abosuletuly fair enough @expung3d , Just wanted to try and contribute back to you guys in some way since ive been using your stuff, and idk it was a simple thing i had so thought it try but ye you right.

**Comment by expung3d** [comment]
No problem. I'm pretty sure we used to have a teleport keybind when EZM first came out. Don't think it's needed now though. 

In future though, check out the contributing guidelines. There's a lot of utility functions in EZM like `MAZ_EZM_fnc_getScreenPosition` that get the mouse position including intersections. Using that, the teleport would work for moving on top of buildings and stuff.

**Comment by expung3d** [comment]
I'm going to close this issue and the PR though. Thank you for trying to add.
