### ISSUE TITLE
[REQUEST] - BIS_fnc_unpackStaticWeapon

### ISSUE THREAD

**Issue by Zaco-Kick** [expung3d/Enhanced-Zeus-Modules#51]
BIS_fnc_unpackStaticWeapon module reminder

**Comment by expung3d** [comment]
This is on you, I want nothing to do with it.

**Comment by Zaco-Kick** [comment]
This is on you, I want nothing to do with it.

**Comment by Zaco-Kick** [comment]
probably too gimmicky
