### ISSUE TITLE
[BUG] - Kicking players in units does not work once EZM has been loaded

### ISSUE THREAD

**Issue by endigma** [expung3d/Enhanced-Zeus-Modules#59]
**Describe the bug**
From what I can tell, players in units cannot be kicked via the playerlist by a server admin once EZM has been loaded, it also transforms `#kick` into `@kick` if typed in the chat. This only happens once EZM has been loaded by the Zeus or Moderator.

**To Reproduce**
Enter a server and take a Zeus slot, have any player attempt to mute a player in a unit or type `#kick` and see it be changed to `@kick`. The playerlist issue only occurs on players who have an active unit.

**Expected behavior**
The playerlist buttons, and the kick command, should function as they do in vanilla.

**Additional context**
Reproduced on 2.1.2 and 2.1.3 on Public Zeus servers several times, with different admins and test subjects.

**Comment by expung3d** [comment]
This has been resolved
