### ISSUE TITLE
[BUG] - Delete bodies module clears intel

### ISSUE THREAD

**Issue by bijx** [expung3d/Enhanced-Zeus-Modules#67]
**Describe the bug**
The new `Create Intel` module creates an intel object that has a `setDamage 1` applied to it since this is how to prevent a player from just picking up the intel straight to their inventory rather than using the custom hold action. But since the object created is technically "dead", we should either have the Delete Bodies and Delete Clutter modules whitelist the intel objects (`Item_Laptop_Unfolded`, `LanD_File1_f`, etc.) or find a better way to prevent players from just picking up the intel.

**To Reproduce**
1. Create a new piece of intel using the `Create Intel` module.
2. Place either the Delete Bodies or Delete Clutter modules.
3. Observe intel is deleted.

**Expected behavior**
The intel should not be deleted since it may affect the mission flow.

**Comment by expung3d** [comment]
There is a utility function for this:
```sqf
[_object] call MAZ_EZM_fnc_ignoreWhenCleaning;
```

**Comment by expung3d** [comment]
Fixed on dev
